"""
Themis Environments — Text Completion Environment

Exposes a gym-like interface for text completion tasks. The agent is prompted
with a text prefix and must complete it to match a target completion,
driving action selection via goal preference (C vector).
"""

from typing import Tuple, Dict, Any, List, Optional, Callable, Union
import random
import torch

from themis.core.distributions import GaussianDist


class TextCompletionEnv:
    """
    TextCompletionEnv

    Presents the agent with a prefix prompt and measures success by how closely
    the generated text matches the target completion.
    """
    def __init__(self, dataset: Optional[List[Tuple[str, str]]] = None):
        # Default corpus of reasoning/completions
        if dataset is None:
            self.dataset = [
                ("The brain is an inference ", "machine"),
                ("Karl Friston is the father of ", "active inference"),
                ("Active inference minimizes variational free ", "energy"),
                ("The statistical boundary of an agent is the ", "markov blanket"),
                ("Expected free energy drives exploration and ", "exploitation"),
                ("Predictive coding computes prediction ", "errors"),
                ("Bayesian model reduction prunes redundant ", "parameters")
            ]
        else:
            self.dataset = dataset
            
        self.current_prefix = ""
        self.current_target = ""
        self.generated_text = ""
        self.step_count = 0
        self.max_steps = 10
        
    def reset(self) -> str:
        """
        Resets environment and returns a random prefix prompt.
        """
        prefix, target = random.choice(self.dataset)
        self.current_prefix = prefix
        self.current_target = target
        self.generated_text = ""
        self.step_count = 0
        return prefix

    def step(self, action_token: str) -> Tuple[str, float, bool, Dict[str, Any]]:
        """
        Processes one generated token and updates completion.
        
        Args:
            action_token: The string token generated by the agent (Layer 1 output).
            
        Returns:
            next_obs: Updated generated text.
            reward: Step reward (negative mismatch cost).
            done: Whether sequence is completed or max steps reached.
            info: Step metadata.
        """
        self.step_count += 1
        
        # Append token to generated text
        self.generated_text += action_token
        
        # Check matching overlap with target
        # Calculate reward: how much of the target has been matched
        target_lower = self.current_target.lower().strip()
        gen_lower = self.generated_text.lower().strip()
        
        # If perfect match
        if gen_lower == target_lower:
            reward = 10.0
            done = True
            matched = True
        # If it is a prefix of the target
        elif target_lower.startswith(gen_lower) and len(gen_lower) > 0:
            reward = 1.0 * len(gen_lower) # progressive reward
            done = False
            matched = False
        else:
            # Mismatch cost
            reward = -1.0
            done = True
            matched = False
            
        if self.step_count >= self.max_steps:
            done = True
            
        info = {
            "target": self.current_target,
            "prefix": self.current_prefix,
            "generated": self.generated_text,
            "matched": matched,
            "step": self.step_count
        }
        
        # Next observation is the concatenation of prefix and generated text
        next_obs = self.current_prefix + self.generated_text
        return next_obs, reward, done, info

    def get_preference(self, encoder: Optional[Callable[[str], GaussianDist]] = None) -> Union[str, GaussianDist]:
        """
        Returns the preference C target.
        If encoder is provided, projects the target text into observation space [batch, obs_dim].
        Otherwise, returns the target text string.
        """
        target_full_text = self.current_prefix + self.current_target
        if encoder is not None:
            return encoder(target_full_text)
        return target_full_text
